language: generic


git:
  submodules: false

env:
  global:
    - WORKSPACE=Example/Coherence.xcworkspace
    - SCHEME="Coherence Test Host"

matrix:
  include:
    -
      os: osx
      osx_image: xcode8.3
      env: 
         - BUILD="pod lint"
    -
      os: osx
      osx_image: xcode8.3
      env: 
         - BUILD="xcodebuild"
         - TEST_DEST="platform=iOS Simulator,OS=10.3,name=iPhone 7"
         - TEST_SDK=iphonesimulator

# Removing other builds until travis fixes their image from https://github.com/travis-ci/travis-ci/issues/7638
#   -
#      os: osx
#      osx_image: xcode8.3
#      env:
#         - BUILD="xcodebuild"
#         - TEST_DEST="platform=iOS Simulator,OS=10.1,name=iPhone 6s"
#         - TEST_SDK=iphonesimulator
#    -
#      os: osx
#      osx_image: xcode8.3
#      env:
#         - BUILD="xcodebuild"
#         - TEST_DEST="platform=iOS Simulator,OS=9.3,name=iPhone 6"
#         - TEST_SDK=iphonesimulator
#    -
#      os: osx
#      osx_image: xcode8.3
#      env:
#         - BUILD="xcodebuild"
#         - TEST_DEST="platform=iOS Simulator,OS=9.0,name=iPhone 4s"
#         - TEST_SDK=iphonesimulator

before_install:
  # Fix travis issue: https://github.com/travis-ci/travis-ci/issues/6307
  - rvm get head --auto-dotfiles || true
  #
  # If there is a Gemfile for this os, install bundler and ask bundler to install the gems
  #
  - |
    if [ -e Gemfile ]; then
       export BUNDLE_GEMFILE=Gemfile
       gem install bundler
       bundler install
    fi

script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
       # Fix travis issue: https://github.com/travis-ci/travis-ci/issues/6307
       rvm get head --auto-dotfiles || true
    fi
  - |
    if [[ "$BUILD" == "swift build"  ]]; then
      set -e
      swift test
      set +e
    fi
  - |
    if [[ "$BUILD" == "pod lint" ]]; then
        set -e
        bundler exec pod repo update
        bundler exec pod lib lint
        set +e
    fi
  - |
    if [[ "$BUILD" == "xcodebuild"  ]]; then
       travis_retry ./.travis/scripts/xcode_build_test.sh
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
